### ISSUE TITLE
Create content for a blog post for the section "Myst support for Nikola"

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/external#33]
The idea of this ticket is to track the creation of content and eventually publish a blog post about Myst support for Nikola.
Check #14 if you need a bigger context.

The proposed outline looks like this (for now, this is evolving content):

# A deep dive into the MyST world
## Overcome the limitations (invitation to next part)

Steps:

- [x] Choose where we are going to publish (Damián's blog, some EBP blog, EBP post linking Damián's post)
- [x] Create a draft
- [x] Revisit the draft
- [x] Publish and ANN

**Comment by damianavila** [comment]
PR with the draft lives here: https://github.com/damianavila/blog/pull/4

@choldgraf, I would appreciate it if you can take a look and provide feedback!

Btw, we have not decided about the first item:

> Choose where we are going to publish (Damián's blog, some EBP blog, EBP post linking Damián's post)

My idea was to publish it on my blog and linking it in the EBP blog section (a la Quantstack), WDYT?

**Comment by choldgraf** [comment]
I just took a pass through the text and left some comments, thanks @damianavila 

For where to post it - I think that content makes more sense on a personal blog rather than on the EBP blog, since it's more about your experience using the tools rather than about the tools themselves.

I'm not sure how we can cross-post using [ablog](https://ablog.readthedocs.io/en/latest/manual/posting-and-listing/), so for now let's just post this on your blog and we can try to figure out how to make an external post list on the EBP blog later

**Comment by damianavila** [comment]
@choldgraf updated the blog post draft, I would appreciate it if you can make another pass on it. Thanks!!

**Comment by damianavila** [comment]
PR is ready, I just need to convert it to ipynb and publish it.

> Publishing on Monday afternoon (I do not like to publish on Fri afternoon when everyone is closing their computers 😉).

**Comment by damianavila** [comment]
Published here: https://damianavila.github.io/blog/posts/a-deep-dive-into-myst-part-1-the-myst-parser-python-api-usage-in-nikola.html
